---
- hosts: localhost
  gather_facts: false
  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
    image_name: hello-go

  pre_tasks:
    - name: Check Minikube's status.
      command: minikube status
      register: minikube_status
      changed_when: false
      ignore_errors: true            # don't want that to fail the whole playbook

    - name: Display Minikube's status.
      debug:
        msg: "{{ minikube_status.stdout }}"

    - name: Start Minikube if it's not running.
      command: minikube start
      when: "not minikube_status.stdout or 'Running' not in minikube_status.stdout"

  tasks:
    # Build the hello-go Docker image inside Minikube's environment
    - name: Get existing image hash.
      shell: |
        eval $(minikube docker-env)
        docker images -q {{ image_name }}
      register: image_hash
      changed_when: false

    - name: Build image if it's not already built.
      shell: |
        eval $(minicube docker-env)
        docker build -t {{ image_name }} ../../hello-go   # path to dir with Dockerfile
      when: not image_hash.stdout

    # Create K8s resources to run hello-go
    - name: Create a Deployment for hello-go
      k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: hello-go-auto
            namespace: default
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: hello-go
            template:
              metadata:
                labels:
                  app: hello-go
              spec:
                containers:
                  - name: hello-go
                    image: "{{ image_name }}"
                    imagePullPolicy: IfNotPresent
                    ports:
                      - containerPort: 8180

    - name: Create a Service for hello-go
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: hello-go-svc-auto
            namespace: default
          spec:
            type: LoadBalancer
            ports:
            - port: 8180
              targetPort: 8180
            selector:
              app: hello-go

  post_tasks:
    - name: Expose Hello Go on the host via Minikube
      command: minikube service hello-go --url=true
      changed_when: false
      register: minikube_service

    - debug:
        msg: "Hello-go URL: {{ minikube_service['stdout_lines'][0] }}"


