---
- hosts: localhost
  gather_facts: false

  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
    replicas: 3

  tasks:
    # k8s_scale is broken in Ansible 2.9 . Will be fixed in 2.10
    # https://github.com/ansible/ansible/pull/59887
    - name: Scale the hello-go with k8s_scale
      k8s_scale:
        api_version: v1
        kind: Deployment
        name: hello-go-auto
        namespace: default
        replicas: "{{ replicas }}"
        wait: false
