apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
          # https://hub.docker.com/_/mysql
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: kiwi-config-map
                key: db
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: kiwi-db-secret
                key: user
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: kiwi-db-secret
                key: password
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: kiwi-db-secret
                key: mysql_root_password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: kiwi-mysql-pv
          mountPath: /var/lib/mysql
      volumes:
      - name: kiwi-mysql-pv
        persistentVolumeClaim:
          claimName: kiwi-mysql-pvc